### ISSUE TITLE
moooooo

### ISSUE THREAD

**Issue by firefish111** [Vera-PLanguage/DASM#18]
![moo](https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Cow_female_black_white.jpg/1200px-Cow_female_black_white.jpg)

**Comment by JBYT27** [comment]
stopppp

**Comment by firefish111** [comment]
@StringentDev get moooed

**Comment by TheQuackyDuck** [comment]
im speechless

**Comment by firefish111** [comment]
@TheQuackyDuck yes

**Comment by StringentDev** [comment]
uuuhhh.... also have no clue what to say except that i have no clue what to say.
